### ISSUE TITLE
Upgrade flutter_bugfender to 3.0.0

### ISSUE THREAD

**Issue by mchudy** [leancodepl/logging_bugfender#14]
We should upgrade the `flutter_bugfender` dependency. The updated library includes updated iOS SDK which removes bitcode from builds. When building with XCode 16 builds with bitcode cannot be uploaded to the AppStore. 

There is a workaround for that (https://medium.com/@abdulahad2024/fixing-bitcode-issues-in-xcode-16-how-to-resolve-invalid-executable-errors-when-uploading-ios-da07a5a39c7c), but it's better to rely on the updated version.

**Comment by mateusz-pietras** [comment]
The dependency got upgraded in https://github.com/leancodepl/logging_bugfender/pull/13
